name: BedWars
version: ${project.version}
main: red.nulled.bedwars.BedWars
api-version: 1.13
authors: [Ami, Atlasted, Hero]
description: A clone of Hypixel's "Bed Wars" game-mode.
commands:
  findDiamond:
    description: Finds all diamond blocks in a certain range around 0,0,0 (hardcoded into plugin) and logs them in the Console and in a HashSet
    usage: /findDiamond
  findEmerald:
    description: Finds all emerald blocks in a certain range around 0,0,0 (hardcoded into plugin) and logs them in the Console and in a HashSet
    usage: /findEmerald