name: BedWars
version: ${project.version}
main: red.nulled.bedwars.BedWars
api-version: 1.13
authors: [Ami, Atlasted, Hero]
description: A clone of Hypixel's "Bed Wars" game-mode.
commands:
  helloworld:
    description: Puts "hello world!" in the chat
    usage: /helloworld